flaskexpense/main/routes.py
from flask import Blueprint, redirect, render_template, url_for
from flask_login import current_user, login_required

main = Blueprint("main", __name__)


@main.route("/")
@main.route("/home")
def index():
    if current_user.is_authenticated:
        return redirect(url_for("expenses.dashboard"))
    return render_template("index.html")


@main.route("/about")
@login_required
def about():
    return render_template("dashboard/about.html")

flaskexpense/plots/routes.py
from datetime import date, datetime, time, timedelta

from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from sqlalchemy import func
from sqlalchemy.sql import label

from flaskexpense import db
from flaskexpense.expenses.forms import DateForm
from flaskexpense.expenses.utils import todate
from flaskexpense.models import Expense
from flaskexpense.plots.utils import plot_bar_chart, plot_pie_chart

plots = Blueprint("plots", __name__)


@plots.route("/bar")
@login_required
def bar_chart():
    form = DateForm()
    end_date = date.today()
    end_date = datetime.combine(end_date, time.min)
    start_date = end_date - timedelta(days=30)
    start = request.args.get("start_date", start_date, type=todate)
    end = request.args.get("end_date", end_date, type=todate)
    form.start_date.data = start
    form.end_date.data = end
    if form.validate():
        start = form.start_date.data
        end = form.end_date.data
        return redirect(url_for("bar_chart", start=start, end=end))
    expenses = (
        db.session.query(Expense.category, label("total", func.sum(Expense.price)))
        .filter_by(user=current_user)
        .filter(Expense.date.between(start, end))
        .group_by(Expense.category)
        .order_by("total")
        .all()
    )
    if not expenses:
        return render_template("dashboard/plot.html", form=form)
    categories = []
    totals = []
    for category, total in expenses:
        categories.append(category)
        totals.append(total)

    script, div = plot_bar_chart(totals, categories)
    return render_template("dashboard/plot.html", script=script, div=div, form=form)


@plots.route("/pie")
@login_required
def pie_chart():
    form = DateForm()
    end_date = date.today()
    end_date = datetime.combine(end_date, time.min)
    start_date = end_date - timedelta(days=30)
    start = request.args.get("start_date", start_date, type=todate)
    end = request.args.get("end_date", end_date, type=todate)
    form.start_date.data = start
    form.end_date.data = end
    if form.validate():
        start = form.start_date.data
        end = form.end_date.data
        return redirect(url_for("pie_chart", start=start, end=end))
    expenses = (
        db.session.query(Expense.category, label("total", func.sum(Expense.price)))
        .filter_by(user=current_user)
        .filter(Expense.date.between(start, end))
        .group_by(Expense.category)
        .order_by("total")
        .all()
    )
    if not expenses:
        return render_template("dashboard/plot.html", form=form)
    x = {}
    for category, total in expenses:
        x[category] = round(total, 2)

    script, div = plot_pie_chart(x)
    return render_template("dashboard/plot.html", script=script, div=div, form=form)

flaskexpense/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <link rel='stylesheet' href="{{url_for('static', filename='dashboard.css')}}" />
    <title>Money Tracker</title>
</head>

<body>
    <!-- sidebar -->
    <div class="ui sidebar inverted vertical menu sidebar-menu" id="sidebar">
        <div class="item"></div>
        <a href="{{url_for('expenses.dashboard')}}" class="item">
            <div>
                <i class="icon book"></i>
                Expenses
            </div>
        </a>

        <div class="item">
            <div class="header">
                <i class="icon chart line"></i>
                Charts
            </div>
            <div class="menu">
                <a class="item" href="{{url_for('plots.bar_chart')}}">
                    <div><i class="chart bar icon"></i>Bar Charts</div>
                </a>
                <a class="item" href="{{url_for('plots.pie_chart')}}">
                    <div><i class="chart pie icon"></i>Pie Charts</div>
                </a>
            </div>
        </div>

        <a href="{{url_for('main.about')}}" class="item">
            <div>
                <i class="icon question circle"></i>
                About
            </div>
        </a>

    </div>

    <!-- sidebar -->
    <!-- top nav -->

    <nav class="ui top fixed massive inverted menu">
        <div class="left menu">
            <a href="#" class="sidebar-menu-toggler item" data-target="#sidebar">
                <i class="sidebar icon"></i>
            </a>
            <a href="{{url_for('expenses.dashboard')}}" class="header item">
                Money Tracker
            </a>
        </div>

        <div class="right menu">
            <div class="ui dropdown item">
                <i class="user cirlce icon"></i>
                <div class="menu">
                    <a href="{{url_for('users.account')}}" class="item">
                        <i class="info circle icon"></i> Profile</a>
                    <a href="{{url_for('users.logout')}}" class="item">
                        <i class="sign-out icon"></i>
                        Logout
                    </a>
                </div>
            </div>
        </div>
    </nav>

    <!-- top nav -->

    <div class="pusher">
        <div class="main-content">
            {% block content %}
            {% endblock %}
        </div>
    </div>



    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.ui.dropdown').dropdown();
            $('.sidebar-menu-toggler').on('click', function () {
                var target = $(this).data('target');
                $(target)
                    .sidebar({
                        dinPage: true,
                        transition: 'overlay',
                        mobileTransition: 'overlay'
                    })
                    .sidebar('toggle');
            });
        });
    </script>
    <script>
        $('.ui.modal')
            .modal('attach events', '.ui.negative.button', 'show');
    </script>
</body>

</html>

flaskexpense/templates/index.html
{% extends 'layout.html' %}
{% block nav%}
<a class="item active" href="{{url_for('main.index')}}">Home</a>
<a class="item" href="{{url_for('users.login')}}">Sign In</a>
{% endblock%}
{% block content %}
<h1 class=" ui inverted header">Money Tracker</h1>
<p>
    An expense tracker web app built with python flask
</p>
<a class="ui huge button" href="{{url_for('users.register')}}">Sign Up</a>
{% endblock %}

flaskexpense/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type='text/css'
        href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='index.css')}}">
    <title>Money Tracker</title>
</head>

<body>
    <div class="ui inverted vertical center aligned segment">
        <nav class="ui container">
            <h1 class="ui inverted header">Money Tracker</h1>
            <div class="ui borderless inverted compact menu">
                {% block nav%}
                {% endblock %}
            </div>
        </nav>
        <div class="ui content container">
            {% block content%}
            {% endblock %}
        </div>
    </div>
</body>

</html>