flaskexpense/expenses/routes.py
from datetime import date, datetime, time, timedelta

from flask import Blueprint, redirect, render_template, request, url_for, abort
from flask_login import current_user, login_required
from sqlalchemy import func
from sqlalchemy.sql import label

from flaskexpense import db
from flaskexpense.expenses.forms import DateForm, ExpenseForm
from flaskexpense.expenses.utils import todate
from flaskexpense.models import Expense

expenses = Blueprint("expenses", __name__)


@expenses.route("/dashboard")
@login_required
def dashboard():
    form = DateForm()
    end_date = date.today()
    end_date = datetime.combine(end_date, time.min)
    start_date = end_date - timedelta(days=30)
    start = request.args.get("start_date", start_date, type=todate)
    end = request.args.get("end_date", end_date, type=todate)
    form.start_date.data = start
    form.end_date.data = end
    if form.validate():
        start = form.start_date.data
        end = form.end_date.data
        return redirect(url_for("expenses.dashboard", start=start, end=end))
    page = request.args.get("page", 1, type=int)
    show_expenses = (
        Expense.query.filter_by(user=current_user)
        .filter(Expense.date.between(start, end))
        .order_by(Expense.date.desc())
        .paginate(page=page, per_page=8)
    )
    total_price = (
        db.session.query(func.sum(Expense.price).label("total"))
        .filter_by(user=current_user)
        .filter(Expense.date.between(start, end))
        .first()
    )[0]
    for expense in show_expenses.items:
        expense.date = expense.date.date()
    return render_template(
        "dashboard/dashboard.html",
        expenses=show_expenses,
        total_price=total_price,
        form=form,
    )


@expenses.route("/expense/new", methods=["GET", "POST"])
@login_required
def new_expense():
    form = ExpenseForm()
    if form.validate_on_submit():
        expense = Expense(
            name=form.name.data,
            date=form.date.data,
            category=form.category.data,
            price=form.price.data,
            user=current_user,
        )
        db.session.add(expense)
        db.session.commit()
        return redirect(url_for("expenses.dashboard"))
    return render_template("dashboard/create.html", form=form, form_title="Add Expense")


@expenses.route("/expense/<int:expense_id>/update", methods=["GET", "POST"])
@login_required
def update_expense(expense_id):
    expense = Expense.query.get_or_404(expense_id)
    if expense.user != current_user:
        abort(403)
    form = ExpenseForm()
    if form.validate_on_submit():
        expense.name = form.name.data
        expense.date = form.date.data
        expense.category = form.category.data
        expense.price = form.price.data
        db.session.commit()
        return redirect(url_for("expenses.dashboard"))
    elif request.method == "GET":
        form.name.data = expense.name
        form.date.data = expense.date
        form.category.data = expense.category
        form.price.data = expense.price
    return render_template(
        "dashboard/create.html", form=form, form_title="Edit Expense"
    )


@expenses.route("/expense/<int:expense_id>/delete", methods=["GET", "POST"])
@login_required
def delete_expense(expense_id):
    expense = Expense.query.get_or_404(expense_id)
    if expense.user != current_user:
        abort(403)
    db.session.delete(expense)
    db.session.commit()
    return redirect(url_for("expenses.dashboard"))

flaskexpense/plots/routes.py
from datetime import date, datetime, time, timedelta

from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from sqlalchemy import func
from sqlalchemy.sql import label

from flaskexpense import db
from flaskexpense.expenses.forms import DateForm
from flaskexpense.expenses.utils import todate
from flaskexpense.models import Expense
from flaskexpense.plots.utils import plot_bar_chart, plot_pie_chart

plots = Blueprint("plots", __name__)


@plots.route("/bar")
@login_required
def bar_chart():
    form = DateForm()
    end_date = date.today()
    end_date = datetime.combine(end_date, time.min)
    start_date = end_date - timedelta(days=30)
    start = request.args.get("start_date", start_date, type=todate)
    end = request.args.get("end_date", end_date, type=todate)
    form.start_date.data = start
    form.end_date.data = end
    if form.validate():
        start = form.start_date.data
        end = form.end_date.data
        return redirect(url_for("bar_chart", start=start, end=end))
    expenses = (
        db.session.query(Expense.category, label("total", func.sum(Expense.price)))
        .filter_by(user=current_user)
        .filter(Expense.date.between(start, end))
        .group_by(Expense.category)
        .order_by("total")
        .all()
    )
    if not expenses:
        return render_template("dashboard/plot.html", form=form)
    categories = []
    totals = []
    for category, total in expenses:
        categories.append(category)
        totals.append(total)

    script, div = plot_bar_chart(totals, categories)
    return render_template("dashboard/plot.html", script=script, div=div, form=form)


@plots.route("/pie")
@login_required
def pie_chart():
    form = DateForm()
    end_date = date.today()
    end_date = datetime.combine(end_date, time.min)
    start_date = end_date - timedelta(days=30)
    start = request.args.get("start_date", start_date, type=todate)
    end = request.args.get("end_date", end_date, type=todate)
    form.start_date.data = start
    form.end_date.data = end
    if form.validate():
        start = form.start_date.data
        end = form.end_date.data
        return redirect(url_for("pie_chart", start=start, end=end))
    expenses = (
        db.session.query(Expense.category, label("total", func.sum(Expense.price)))
        .filter_by(user=current_user)
        .filter(Expense.date.between(start, end))
        .group_by(Expense.category)
        .order_by("total")
        .all()
    )
    if not expenses:
        return render_template("dashboard/plot.html", form=form)
    x = {}
    for category, total in expenses:
        x[category] = round(total, 2)

    script, div = plot_pie_chart(x)
    return render_template("dashboard/plot.html", script=script, div=div, form=form)

flaskexpense/templates/dashboard/about.html
{% extends 'base.html' %}
{% block content %}
<div class="ui inverted segment">
    <H1>Money Tracker</H1>
    <p>Money tracker is an web app to help you track your personal expenses.</p>
    <p> Get a 360-degree view of your money.</p>
    <p>And visualize your spending with analytics tools</p>
</div>
{% endblock %}

flaskexpense/templates/dashboard/account.html
{% extends 'base.html' %}
{% block content %}
<div class="ui grid stackable padded">
    <div class="column">
        <table class="ui inverted celled table">
            <thead>
                <tr>
                    <th class="collapsing">
                        <H2>User Information</H2>
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <h3>Username</h3>
                    </td>
                    <td>{{current_user.username}}</td>
                </tr>
                <tr>
                    <td>
                        <h3>User Email</h3>
                    </td>
                    <td>{{current_user.email}}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock%}

flaskexpense/templates/dashboard/create.html
{% extends 'base.html' %}
{% block content %}
<div class="ui grid stackable padded">
    <div class="column">
        <form class="ui inverted form error" method="POST" action="" id='create'>
            {{form.hidden_tag()}}
            <div class="ui dividing inverted header">
                <h2>{{form_title}}</h2>
            </div>

            <div class="field">
                <label>{{form.name.label}}</label>
                {% if form.name.errors %}
                {{ form.name (placeholder='Name')}}
                <div class="ui error message">
                    {% for error in form.name.errors %}
                    <p>{{ error }}</p>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.name (placeholder='Name')}}
                {% endif %}
            </div>
            <div class="field">
                <label>{{form.date.label}}</label>
                {% if form.date.errors %}
                {{ form.date (placeholder='YYYY-MM-DD')}}
                <div class="ui error message">
                    {% for error in form.date.errors %}
                    <p>{{ error }}</p>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.date (placeholder='YYYY-MM-DD')}}
                {% endif %}
            </div>
            <div class="field">
                <label>{{form.category.label}}</label>
                {% if form.category.errors %}
                {{ form.category }}
                <div class="ui error message">
                    {% for error in form.category.errors %}
                    <p>{{ error }}</p>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.category }}
                {% endif %}
            </div>
            <div class="field">
                <label>{{form.price.label}}</label>
                {% if form.price.errors %}
                {{ form.price (placeholder='Amount')}}
                <div class="ui error message">
                    {% for error in form.price.errors %}
                    <p>{{ error }}</p>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.price (placeholder='Amount')}}
                {% endif %}
            </div>
            {{form.submit (class='ui button')}}
        </form>
    </div>
</div>
{% endblock %}

flaskexpense/templates/dashboard/dashboard.html
{% extends 'base.html' %}
{% block content %}
<div class="ui grid stackable padded">
    <div class="column">
        <div class="ui inverted form error" id='dates'>
            {{form.hidden_tag()}}
            <form class="inline fields" method="GET" action=''>
                <div class="field">
                    <label>{{form.start_date.label}}</label>
                    {{form.start_date}}
                </div>
                <div class="field">
                    {% if form.end_date.errors %}
                    <label>{{form.end_date.label}}</label>
                    {{ form.end_date}}
                    <div class="ui error message">
                        {% for error in form.end_date.errors %}
                        <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                    {% else %}
                    <label>{{form.end_date.label}}</label>
                    {{ form.end_date}}
                    {% endif %}
                </div>
                <button class="ui button" type="submit">Show</button>
            </form>
        </div>
        <table class="ui inverted table">
            <thead>
                <tr>
                    <th colspan="6">
                        <H2>Expense History</H2>
                        <a href="{{url_for('expenses.new_expense')}}">
                            <i class="inverted plus circle icon"></i>
                            Add Expense
                        </a>
                    </th>
                </tr>
                <tr>
                    <th>Name</th>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Amount</th>
                    <th class="collapsing"></th>
                    <th class="collapsing"></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <h3>Total</h3>
                    </td>
                    <td></td>
                    <td></td>
                    <td>
                        <h4>{{'%0.2f' % total_price|float}}</h4>
                    </td>
                </tr>
                {% for expense in expenses.items %}
                <tr>
                    <td>{{expense.name}}</td>
                    <td>{{expense.date}}</td>
                    <td>{{expense.category}}</td>
                    <td>{{expense.price}}</td>
                    <td class="right aligned collapsing">
                        <form action="{{url_for('expenses.update_expense', expense_id=expense.id)}}" method="GET">
                            <button type="submit" class="ui small vertical animated inverted secondary button"
                                tabindex="0">
                                <div class="hidden content">Edit</div>
                                <div class="visible content">
                                    <i class="inverted edit icon"></i>
                                </div>
                            </button>
                        </form>
                    </td>
                    <td class="right aligned collapsing">
                        <form action="{{url_for('expenses.delete_expense', expense_id=expense.id)}}" method="POST">
                            <button type="submit" class="ui small vertical animated inverted secondary button"
                                tabindex="0">
                                <div class="hidden content">Delete</div>
                                <div class="visible content">
                                    <i class="inverted red trash icon"></i>
                                </div>
                            </button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="6">
                        <div class="ui right floated inverted pagination menu">
                            {% set start_date = request.args.get('start_date') %}
                            {% set end_date = request.args.get('end_date') %}
                            {% for page_num  in expenses.iter_pages(left_edge = 1, right_edge=1, left_current=1, right_current=2) %}
                            {% if page_num %}
                            {% if expenses.page == page_num%}
                            <a class="primary item"
                                href="{{url_for('expenses.dashboard',page=page_num, start_date=start_date, end_date=end_date)}}">{{page_num}}</a>
                            {% else %}
                            <a class="item"
                                href="{{url_for('expenses.dashboard',page=page_num,start_date=start_date, end_date=end_date)}}">{{page_num}}</a>
                            {% endif %}
                            {% else %}
                            <div class="item">...</div>
                            {% endif %}
                            {% endfor%}
                        </div>
                    </th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
{% endblock%}

flaskexpense/templates/dashboard/plot.html
{% extends 'base.html' %}
{% block content %}
<div class="ui grid stackable padded">
    <div class="column">
        <div class="ui inverted form error" id='dates'>
            {{form.hidden_tag()}}
            <form class="inline fields" method="GET" action=''>
                <div class="field">
                    <label>{{form.start_date.label}}</label>
                    {{form.start_date}}
                </div>
                <div class="field">
                    {% if form.end_date.errors %}
                    <label>{{form.end_date.label}}</label>
                    {{ form.end_date}}
                    <div class="ui error message">
                        {% for error in form.end_date.errors %}
                        <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                    {% else %}
                    <label>{{form.end_date.label}}</label>
                    {{ form.end_date}}
                    {% endif %}
                </div>
                <button class="ui button" type="submit">Show</button>
            </form>
        </div>
        {% if div%}
        {{ div|safe }}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bokeh/2.1.1/bokeh.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bokeh/2.1.1/bokeh-widgets.min.js"></script>
        {{ script|safe }}
        {% else %}
        <h1>No expense during this period</h1>
        {% endif %}
    </div>
</div>
{% endblock%}